### ISSUE TITLE
ModuleNotFoundError: No module named 'mask3d'

### ISSUE THREAD

**Issue by Louis708** [aminebdj/OpenYOLO3D#12]
When I finish the installation and data preparation, I run the evalation script: 
python run_evaluation.py and python single_scene_inference.py
It raises the problem of the import package of mask3d:

Traceback (most recent call last):
  File "/OpenYOLO3D/run_evaluation.py", line 6, in <module>
    from utils import OpenYolo3D
  File "/OpenYOLO3D/utils/__init__.py", line 1, in <module>
    from utils.utils_3d import Network_3D
  File "/OpenYOLO3D/utils/utils_3d.py", line 4, in <module>
    from models.Mask3D.mask3d import get_model, load_mesh, prepare_data, map_output_to_pointcloud, save_colorized_mesh 
  File "/OpenYOLO3D/models/Mask3D/mask3d/__init__.py", line 5, in <module>
    from mask3d.models.mask3d import Mask3D
ModuleNotFoundError: No module named 'mask3d'

**Comment by aminebdj** [comment]
Hello @Louis708 ,

I believe that this is due to a problem while installing mask3d. Did you follow the installation guide in [Installation](https://github.com/aminebdj/OpenYOLO3D/blob/main/docs/Installation.md)?
